version: 0.0
os: linux
files:
<<<<<<< HEAD
  - source: /index.html
    destination: /var/www/html/
=======
  - source: /
    destination: /
>>>>>>> a880282fe5afbbaa8fbd979abcc114a36a7f152f
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

